# Generated by Django 3.1.5 on 2021-01-14 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20210115_0027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Сategory_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_product', models.CharField(db_index=True, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(db_index=True, max_length=40)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='recipes.сategory_product')),
            ],
        ),
    ]
