# Generated by Django 3.1.5 on 2021-01-15 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Count',
        ),
    ]
