# Generated by Django 3.1.5 on 2021-01-16 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20210116_0147'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='recipe',
            table='web_recipe',
        ),
    ]
