# Generated by Django 3.1.5 on 2021-07-06 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_auto_20210706_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='authors',
        ),
    ]
