# Generated by Django 3.1.5 on 2021-07-06 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0018_recipe_author'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='recipe',
            table='web_recipes',
        ),
    ]
