# Generated by Django 3.1.5 on 2021-07-06 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_auto_20210706_2122'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='recipe',
            table=None,
        ),
    ]
