# Generated by Django 3.1.5 on 2021-07-06 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0023_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='photo',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
