# Generated by Django 3.1.5 on 2021-07-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0028_auto_20210710_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
